name: Build (Linux)

on:
  push:
    paths:
      - .github/workflows/build-linux.yml
      - src/**
      - xmake.lua
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        mode: [release, debug]
    runs-on: ubuntu-20.04 # for compatibility.
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Restore xmake cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.xmake
          key: xmake-linux-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-linux-${{ matrix.mode }}-

      - name: Sync with repository
        run: |
          xmake repo -u

      - name: Build for host
        run: |
          xmake f -a x64 -m ${{ matrix.mode }} -p linux -v -y
          xmake -v -y

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: allay-launcher-linux-x64-${{ matrix.mode }}
          path: |
            build/linux/x64/${{ matrix.mode }}
