name: Build (Linux)

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    strategy:
      matrix:
        arch:
          - x86
          - x64
          - arm
          - arm64
          - arm64ec
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v4
        with:
          path: |
            ~/.xmake
          key: xmake-linux-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-linux-

      - run: |
          sudo apt install -y build-essential

      - run: |
          xmake repo -u

      - run: |
          xmake f -a ${{ matrix.arch }} -m release -p linux -v -y

      - run: |
          xmake -v -y

      - uses: actions/upload-artifact@v4
        with:
          name: allay-launcher-linux-${{ matrix.arch }}
          path: |
            build/linux/${{ matrix.arch }}/release